### ISSUE TITLE
[1.18] [Serious-bug] Epilepsy Concern when using True Darkness

### ISSUE THREAD

**Issue by Cixon** [MarkusBordihn/BOs-Player-Companions#18]
**Describe the bug**
It appears to be a horrible flashing that occurs when pairing companions with [True Darkness](https://www.curseforge.com/minecraft/mc-mods/true-darkness).

**Preview**
https://streamable.com/7pce0k

**Comment by MarkusBordihn** [comment]
Thanks for the report. Could you please provide more details to reproduce the issue like version number and steps to reproduce.

I was unfortunately not able to reproduce the issue on 1.18.2, see:
![image](https://user-images.githubusercontent.com/12183293/221556448-8c24d9e1-1fd4-4f21-bbee-436c647dfa59.png)

![image](https://user-images.githubusercontent.com/12183293/221558295-55fe6a13-739b-4c7e-b6e7-9a6afedd9f46.png)

Because True Darkness using Mixin for their effect, I could only disable dynamic lighting on my side if True Darkness is installed and in the case you are in an open field.
But the flickering itself, could be only be solved by the True Darkness mod itself.

**Comment by Cixon** [comment]
> Thanks for the report. Could you please provide more details to reproduce the issue like version number and steps to reproduce.

Hey, sorry. Here's some more context.

**Mods I used that may affect lighting:**

Betterfog-1.18.2-1.1.1.jar
[link](https://www.curseforge.com/minecraft/mc-mods/fog-looks-good-now/files/4282208)
Darkness-forge-mc118-2.0.91.jar 
[link](https://beta.curseforge.com/minecraft/mc-mods/true-darkness/files/3815313)
Oculus-1.4.3a.jar
[link](https://www.curseforge.com/minecraft/mc-mods/oculus/files/4354939)
Player_companions_1.18.2-1.10.0.jar
_(version 1.10.0)_
Rubidium-0.5.4.jar
[link](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4024781)
Starlight-1.0.2+forge.546ae87.jar 
[link](https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/3706539)

**Modpack in question:**
https://www.curseforge.com/minecraft/modpacks/legacy-forge

**FML Version:** 40.2.1

**System Details**
Details:
-Minecraft Version: 1.18.2
-Minecraft Version ID: 1.18.2
-Operating System: Windows 10 (amd64) version 10.0
-Java Version: 17.0.1, Microsoft
-Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
-Memory: 2781870080 bytes (2652 MiB) / 4039114752 bytes (3852 MiB) up to 4294967296 bytes (4096 MiB)
-CPUs: 8
-Processor Vendor: AuthenticAMD
-Processor Name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
-Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
-Microarchitecture: Zen / Zen+
-Frequency (GHz): 2.10
-Number of physical packages: 1
-Number of physical CPUs: 4
-Number of logical CPUs: 8
-Graphics card #0 name: AMD Radeon RX Vega 10 Graphics
-Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
-Graphics card #0 VRAM (MB): 2048.00
-Graphics card #0 deviceId: 0x15d8
-Graphics card #0 versionInfo: DriverVersion=31.0.12040.1000
-Graphics card #1 name: AMD Radeon RX 560X Series
-Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
-Graphics card #1 VRAM (MB): 4095.00
-Graphics card #1 deviceId: 0x67ef
-Graphics card #1 versionInfo: DriverVersion=31.0.12040.1000
-Memory slot #0 capacity (MB): 8192.00
-Memory slot #0 clockSpeed (GHz): 2.67
-Memory slot #0 type: DDR4
-Virtual memory max (MB): 14274.64
-Virtual memory used (MB): 12114.85
-Swap memory total (MB): 8192.00
-Swap memory used (MB): 3504.71
-**JVM Flags:** 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m

Loaded Shaderpack: (off)
NEC status: No NEC detected
ModLauncher: 9.1.3+9.1.3+main.9b69c82a
ModLauncher launch target: forgeclient
ModLauncher naming: srg
ModLauncher services: 
mixin PLUGINSERVICE
eventbus PLUGINSERVICE 
slf4jfixer PLUGINSERVICE 
object_holder_definalize PLUGINSERVICE 
runtime_enum_extender PLUGINSERVICE 
capability_token_subclass PLUGINSERVICE 
accesstransformer PLUGINSERVICE 
runtimedistcleaner PLUGINSERVICE 
mixin TRANSFORMATIONSERVICE 
fml TRANSFORMATIONSERVICE

**Comment by Cixon** [comment]
> Because True Darkness using Mixin for their effect, I could only disable dynamic lighting on my side if True Darkness is installed and in the case you are in an open field.

I think this will work for now or at least until we can find the root of the problem. I love this companion because it serves a great purpose in my mod-pack. Having that cute companion to aid players through the nostalgic darkness fits perfectly but I also don't want to inflict harm on epileptic users.

> But the flickering itself, could be only be solved by the True Darkness mod itself.

Oohh :(( what do you recommend I do for now? 👀 
what do you recommend i say to them that the devs will understand?

**Comment by MarkusBordihn** [comment]
I think I found a fix for this. The new lighting logic will slowly fade out the light source, which works fine with the Darkness mod during my tests and avoids any kind of flickering.

Let me know if you are still able to reproduce the issue with the new  6.0.0 version and I'm happy to take a further look into this. Thanks.

**Comment by Cixon** [comment]
>Mods I used that may affect lighting
>Betterfog-1.18.2-1.1.1.jar
>[link](https://www.curseforge.com/minecraft/mc-mods/fog-looks-good-now/files/4282208)
>Darkness-forge-mc118-2.0.91.jar 
>[link](https://beta.curseforge.com/minecraft/mc-mods/true-darkness/files/3815313)
>Oculus-1.4.3a.jar
>[link](https://www.curseforge.com/minecraft/mc-mods/oculus/files/4354939)
>Player_companions_1.18.2-1.10.0.jar
>_(version 1.10.0)_
>Rubidium-0.5.4.jar
>[link](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4024781)
>Starlight-1.0.2+forge.546ae87.jar 
>[link](https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/3706539)

Hello! I tested this with **the new 6.0.0** update on the client only. This issue also still occurs in a single player environment.
I do appreciate the fading, that does help a lot. I'm not epileptic however this does help, I'm sensitive to very sudden light movements and such as I will get a migraine so I thank you a lot for implementing this, I appreciate this a lot.

**Here's the previews** 
Preview 1 (server): https://streamable.com/zlm2yd

Preview 2 (singleplayer): https://streamable.com/428tjs

I think you've done what you can. I do not want you to change too much I think the most you can do is have the **untamed** fireflies have a low static light source no matter what and add the pulsation light effect so it's never completely dark upon discovering the fireflies. I will need to reach out to the creators of True Darkness to issue some sort of fix. I will mention this ticket.

This issue seems to only have a horrific effect when the moon phases are at the darkest overcast.
Accomplished by setting the time to midnight and then triggering this command 4 times:
_/time add 24000_
